# Generated by Django 5.1.2 on 2024-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_stamp',
            field=models.DateField(auto_now=True),
        ),
    ]
