# Generated by Django 5.1.2 on 2024-10-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_stamp',
            field=models.DateField(),
        ),
    ]
