# Generated by Django 5.1.2 on 2024-10-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='staff_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='staff_last_name',
            new_name='last_name',
        ),
    ]
